# Generated by Django 3.0.4 on 2020-03-26 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('ziel', models.TextField(verbose_name='Ziel')),
                ('grund', models.CharField(max_length=200, verbose_name='Grund')),
                ('von', models.TimeField(verbose_name='Von')),
                ('bis', models.TimeField(verbose_name='Bis')),
                ('kostenstelle', models.CharField(max_length=12, verbose_name='Kostenstelle')),
                ('projekt', models.CharField(max_length=200, verbose_name='Projekt')),
            ],
        ),
    ]
